#ifndef EVENT_CONSTANTS_H
#define EVENT_CONSTANTS_H

//G indica que se trata de un evento no devuelto por el sistema con glfw, sino un gesto
enum Event{
	EVENT_NULL,
	MOUSE_PRESS_LEFT,
	MOUSE_PRESS_RIGHT,
	MOUSE_RELEASE_LEFT,
	MOUSE_RELEASE_RIGHT,
	G_MOUSE_IS_PRESSED_LEFT,
	G_MOUSE_IS_PRESSED_RIGHT,
	KEY_PRESS_SPACE,
	KEY_PRESS_Q,
	KEY_PRESS_W,
	KEY_PRESS_S,
	KEY_PRESS_A,
	KEY_PRESS_D,
	KEY_RELEASE_W,
	KEY_RELEASE_S,
	KEY_RELEASE_A,
	KEY_RELEASE_D,
	G_KEY_IS_PRESSED_W,
	G_KEY_IS_PRESSED_S,
	G_KEY_IS_PRESSED_A,
	G_KEY_IS_PRESSED_D,
	KEY_PRESS_2,
	KEY_PRESS_ENTER,
	KEY_PRESS_SHIFT,
	KEY_PRESS_UP,
	KEY_PRESS_DOWN,
	KEY_PRESS_RIGHT,
	KEY_PRESS_LEFT,
	KEY_RELEASE_UP,
	KEY_RELEASE_DOWN,
	KEY_RELEASE_LEFT,
	KEY_RELEASE_RIGHT,
	G_KEY_IS_PRESSED_UP,
	G_KEY_IS_PRESSED_DOWN,
	G_KEY_IS_PRESSED_RIGHT,
	G_KEY_IS_PRESSED_LEFT,
	G_COMBO_1,
	G_CLICK,
	G_DRAG
};

#endif